# Generated by Django 4.2.5 on 2023-11-01 14:25

from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('prix', models.FloatField()),
                ('intitule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.commande')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.service')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeArticle',
            fields=[
                ('comArt', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('montant', models.FloatField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.article')),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.commande')),
            ],
        ),
    ]
