# Generated by Django 4.2.5 on 2023-10-17 10:42

from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continant',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
                ('continant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.continant')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.CharField(db_index=True, default=ulid.ulid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.ville')),
            ],
        ),
    ]
